# Generated by Django 5.0 on 2024-02-27 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INQUIRY", "Inquiry"),
                            ("ONBOARDING", "Onboarding"),
                            ("ACTIVE", "Active"),
                            ("CHURNED", "Churned"),
                        ],
                        default="INQUIRY",
                        max_length=50,
                    ),
                ),
                (
                    "primary_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "primary_state",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("address_line_1", models.CharField(max_length=100)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=8)),
                ("zip_code", models.CharField(max_length=16)),
                (
                    "patient",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientCustomData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("NUMBER", "Number")],
                        default="TEXT",
                        max_length=50,
                    ),
                ),
                ("field_value", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_data",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
