# Generated by Django 5.0 on 2024-02-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_auto_20240202_0950"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="addresses",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="patients",
                to="patients.patientaddress",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
