# Generated by Django 5.0 on 2024-02-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_alter_patient_addresses_alter_patient_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="primary_city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="primary_state",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
